### ISSUE TITLE
Commds help

### ISSUE THREAD

**Issue by Alexey-T** [zizhongyan/StataImproved#1]
What this means?
`Automated Section Header, Comments toggle, and To Do List.`

what is it, pls write some help about it? It is some command of plugin. Or... Some event.

**Comment by zizhongyan** [comment]
Hi Alex, Sorry for the confusing. I wanted to say this was snippet for making comments. But some of my friends did not understand "snippets". Anyway I have just changed the wording to "Auto-completion"
