### ISSUE TITLE
Port to Cud

### ISSUE THREAD

**Issue by Alexey-T** [zizhongyan/StataImproved#2]
Im gonna to create simple Cudatext plugin. As start. Simple: it can only send do-file to Stata. 
Will you see my plg code, to test it on Cudatext and Stata? 
I dont have do-file.

**Comment by zizhongyan** [comment]
Okay

**Comment by Alexey-T** [comment]
Empty/filler plugin. pls try. see readme.txt, 1) event on press ` works. 2) command "Exec curr text" not works, it prints debug to Console panel. (Console panel: Ctrl+tick in Cudatext)

- install Cud
- install in AddonManager: "install from Github"
- run Plugins - Install from Github
- enter URL of plg:
https://github.com/CudaText-addons/cuda_stata_helper
- new plg installed: Stata Helper

**Comment by Alexey-T** [comment]
bump.

**Comment by Alexey-T** [comment]
progress?

**Comment by Alexey-T** [comment]
Cudatext is improved in last month. For MacOS too. maybe continue the port?
