### ISSUE TITLE
Sending do files to Stata 15

### ISSUE THREAD

**Issue by pjpaulpj** [zizhongyan/StataImproved#5]
Hi,

I have two versions of Stata installed on my system-- Stata 14 and Stata 15. Code execution by the plugin using Control + D always sends the code to Stata 14.
How can I fix this such that the code is sent by default to Stata 15?  I'd prefer to not delete Stata 14.

**Comment by zizhongyan** [comment]
Hi,

Many thanks for the suggestion.

I have just added the basic supports for Stata 15, and launched a new release. 

Hence, by default, it will now send the code to Stata 15 if both Stata 15 and Stata 14 are installed on a Mac. 
 
Basically, if different versions of Stata are installed, the plugin can only find the most updated version of Stata.
